server.port=8081
spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://admin:K6YOG7NRTDUReu2b@cluster0.lbdpg4f.mongodb.net/newsmartsystem_db?retryWrites=true&w=majority&appName=Cluster0